include:
  - local: 'src/nouveau/ci/gitlab-ci-inc.yml'

nvk-ga106-vkcts-valve:
  extends:
    - .b2c-x86_64-test-vk
    - .nvk-vkcts
    - .nvk-ga106-valve
    - .nvk-valve-manual-rules
  timeout: 2h
  variables:
    B2C_TIMEOUT_BOOT_MINUTES: 115
    B2C_TIMEOUT_OVERALL_MINUTES: 115
    HWCI_START_WESTON: 1
